### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by davidbucka** [fabiospampinato/vscode-open-in-gittower#1]
First, thank you for this nice little helper!

I think it would be nice if the repo opens in a new tab or closes the other instances of Tower before opening a new one, because I have to switch very often between repos at work and I end up having like 10 different Tower instances open simultaneously.

**Comment by fabiospampinato** [comment]
Thanks for the suggestions. 

I think the easiest solution to this is simply to do a `cmd+w` when you're done with Tower, instead of minimizing it.

Alternatives:
- **New tab**: unfortunately the `gittower` command line app doesn't have a `--tab` option, so we would have to create a new tab via an applescript, but if that repository is already opened the newly created tab will be useless, and won't be closed automatically.
- **Closing other windows**: there could very well be an option for this 🤔 fell free to submit a PR for it if you have the time.

**Comment by fabiospampinato** [comment]
Closing as I don't see a way to implement it, and I'm not sure it should be implemented anyway.
